config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  resources :costumes do
    resources :bookings
    resources :reviews, only: [:create]
  end
  resources :bookings, only: [:index, :edit, :update] do
    member do
      get :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :costume
  belongs_to :user

  enum status: { pending: 0, confirmed: 1, rejected: 2 }
  validates :user, presence: true
  validates :costume, presence: true
  validates :end_date, presence: true
  validates :start_date, presence: true

  def total_days
    (self.end_date - self.start_date).to_i
  end

  def total_price
    return 0 if Booking.all.empty?
    (self.costume.price * total_days)
  end
end

app/models/costume.rb
class Costume < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  has_many_attached :photos

  CATEGORIES = ['Heroes', 'Horror', 'Movies', 'Animals', 'Anime', 'TV Show', 'Historical Figures', 'Princess', 'Cartoon']
  validates :name, presence: true
  validates :user, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :price, presence: true
  # validates :photo, presence: true
  # validates :availability, presence: true
  def average_rating
    return 'n/a' if reviews.empty?
    #return 0 if reviews.empty?
    (reviews.pluck(:rating).sum / reviews.count.to_f).round(2)
  end

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category, :description ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :costume

  validates :costume, presence: true
  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :costumes
  has_many :bookings
  has_one_attached :photo

  ADDRESSES = ["Tokyo Tower", "Tokyo Skytree", "Tokyo Stadium", "Shibuya Stations", "Shinjuku Station", "Tokyo Station", "Shibuya Miyashita Park"]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :confirm]

  def index
    @bookings = Booking.all
  end
  def edit

  end

  def update
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def confirm
    @booking.status = 1
    @booking.save
    redirect_to bookings_path, notice: "Booking confirmed!"
  end

  def new
    @booking = Booking.new
  end

  def create
    @costume = Costume.find(params[:costume_id])
    @booking = Booking.new(booking_params)
    @booking.costume = @costume
    @booking.user = current_user
    @booking.status = 0
    if @booking.save
      redirect_to costume_path(@costume), notice: "Booked costume! Waiting for confirmation."
    else
      render "costumes/show"
    end
  end

  # def destroy
  #   @booking.destroy
  #   redirect_to bookings_path
  # end
  private

  def set_booking
   @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :set_costume, only: [:show, :update, :destroy]
  # visitors can see index page, otherwise will ask for login
  

  def index
    if params[:query].blank?
      @costumes = Costume.where(category: params[:category])
    else
      @costumes = Costume.search_by_name_and_category(params[:query])
      @query = params[:query]
    end
    # @markers = User.all.geocoded.map do |user|
    #   {
    #     lat: user.latitude,
    #     lng: user.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
    #     image_url: helpers.asset_url('ghost.png')
    #   }
    # end
  end

  def show
    @query = params[:query]
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @costume = Costume.new
    @categories = ["heroes", "movies", "horror", "animals", "anime", "TV show", "cartoon", "princess", "historical figure"]
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user = current_user
    if @costume.save
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end

  def destroy
    @costume.destroy
    redirect_to costumes_path
  end
private

  def set_costume
    @costume = Costume.find(params[:id])
  end

  def costume_params
    params.require(:costume).permit(:name, :user, :category, :description, :price, :photo, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def profile
    @user = current_user
    @bookings = Booking.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_costume, except: [:destroy]

  def new
  end

  def create
    @review = Review.new(review_params)
    @review.costume = @costume

    if @review.save
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end
  private

  def find_costume
    @costume = Costume.find(params[:costume_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_show_card.html.erb
<div class="container d-flex flex-wrap">
  <% @bookings.sort_by(&:total_price).reverse.each do |booking| %>
    <div class="card-trip m-2">
      <%= cl_image_tag booking.costume.photo.key, width: 350, height: 200, gravity: :face, crop: :fill  %>
      <div class="card-trip-infos">
        <div>
          <h2><%= "Owner@me.com"%></h2>
          <p><%= booking.costume.name%></p>
          <p><%= booking.start_date%></p>
          <p><%= booking.end_date%></p>
          <p><%= booking.total_days %> day rental at $<%= booking.costume.price %> a day</p>
        </div>
        <h2 class="card-trip-pricing"><%= "$#{booking.total_price}/total"%></h2>
        <% if booking.costume.user.photo.attached? %>
            <%= cl_image_tag booking.costume.user.photo.key, class: "avatar-bordered card-trip-user", gravity: :face, crop: :fill %>
        <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/random" class="card-trip-user avatar-bordered" />
        <% end %>
        <% if @user.email == 'irvin-alexanders@outlook.com' %>
          <h2><%= booking.status %></h2>
        <% elsif @booking.user == current_user %>
          <%= link_to "Confirm Booking", confirm_booking_path(booking), class: "btn btn-outline-success" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/_form.html.erb
<div class="card p-3">
  <div class="container justify-content-center">
    <h4><strong><%= @costume.name %></strong></h4>
    <h6><strong><%= @costume.category %></strong></h6>
    <p><%= @costume.description %></p>
    <p><strong>$<%= @costume.price %></strong></p>
    <p><em><small><%= @costume.user.address %></strong></em></p>
    <h6><%= @costume.user.email %></h6>
    <%= simple_form_for [@costume, @booking] do |f| %>
      <%= f.input :start_date, html5: true, required: false %>
      <%= f.input :end_date, html5: true, required: false%>
      <%= f.submit class: "btn btn-outline-danger btn-block"  %>
    <% end %>
    <div class="containter my-3">
      <%= link_to 'Back', costumes_path(query: params[:query]), class: "btn btn-outline-danger" %>
      <%= link_to 'Home', root_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/bookings/_user_profile.html.erb
<div class="container-box d-flex flex-wrap justify-content-center">
  <div class="card-trip m-2">
      <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, id: "user-image", gravity: :face, crop: :fill, width: 450, height: 300 %>
      <% else %>
          <img src="https://kitt.lewagon.com/placeholder/users/random" class="card-trip-user avatar-bordered" />
      <% end %>
    <div class="my-2 p-3">
        <div>
          <div class="p-1 d-flex justify-content-between">
            <h2>Username:</h2>
              <p><%=current_user.first_name%> <%= current_user.last_name %></p>
          </div>
          <div class="p-1 d-flex justify-content-between">
            <h2>Email:</h2>
              <p><%=current_user.email%></p>
          </div>
          <div class="p-1 d-flex justify-content-between">
            <h2>Location:</h2>
              <p><%= current_user.address%></p>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="d-flex container-fluid my-0 flex-grow-1 align-content-center">
  <div class="mr-5 mt-4">
    <ul class="tabs-underlined" id="myTab" role="tablist">
      <li class="row nav-item" role="presentation">
        <a class="active tab-underlined" id="my-costumes-tab" data-toggle="tab" href="#bookings" role="tab" aria-controls="home" aria-selected="true"><h5 style="color: green;">Lending</h5></a>
      </li>
      <li class="row nav-item" role="presentation">
        <a class="tab-underlined" id="my-bookings-tab" data-toggle="tab" href="#requests" role="tab" aria-controls="profile" aria-selected="false"><h5 style="color: green;">Renting</h5></a>
      </li>
      <li class="row nav-item" role="presentation">
        <a class="tab-underlined" id="profile-tab" data-toggle="tab" href="#converstions" role="tab" aria-controls="converstion" aria-selected="false"><h5 style="color: green;">Profile</h5></a>
        </li>
    </ul>
  </div>
     <div class="mx-auto">
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade py-3 show active" id="bookings" role="tabpanel" aria-labelledby="my-costumes-tab">
        <div class="container d-flex flex-wrap">
          <% current_user.costumes.each do |costume| %>
            <%= render "costumes/costume_show_card", costume: costume %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/costumes/_costume_show_card.html.erb
<div class="card m-2">
  <%= cl_image_tag costume.photo.key, width: 350, height: 200, gravity: :face, crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2><%=costume.name%></h2>
      <p><%= costume.description%></p>
    </div>
      <h2 class="card-trip-pricing"><%= "$#{costume.price}/day"%></h2>
      <% if costume.user != current_user%>
        <% if costume.user.photo.attached? %>
          <%= cl_image_tag costume.user.photo.key, class: "avatar-bordered card-trip-user", gravity: :face, crop: :fill %>
        <% else %>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        <% end %>
      <% end %>
  </div>
</div>

app/views/costumes/_info_window.html.erb
<% user.costumes.each do |costume| %>
  <div class="card mb-2 p-3">
    <div>
      <%= cl_image_tag costume.photo.key, width: 150, height: 100, gravity: :face, crop: :fill %>
        <h2><%= costume.name %></h2>
        <p><%= costume.description %></p>
        <p><%= user.address %></p>
    </div>
      <h2 class="card-trip-pricing">$<%= costume.price %></h2>
        <% if costume.user.photo.attached? %>
          <%= cl_image_tag costume.user.photo.key, class: "avatar-bordered card-trip-user", gravity: :face, crop: :fill %>
        <% else %>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        <% end %>
      <%= link_to costume_path(costume) do %>
        <div class="">
          <button type="button" class="btn btn-outline-danger btn-block m-1 btn-sm">Rent me!</button>
        </div>
      <% end %>
  </div>
<% end %>

app/views/costumes/_new_costume_form.html.erb
<div class="container d-flex justify-content-center">
  <div class="card card-product-grid p-3 m-3" style="">
    <h1 style="font-family: arial;"><strong>Add new costume</strong></h1>
    <%= simple_form_for [@costume] do |f| %>
      <%= f.input :name, required: false %>
      <%= f.input :description, required: false %>
      <%= f.input :price, required: false %>
      <%= f.input :category, required: false, collection: Costume::CATEGORIES, include_blank: false, style: "m-1" %>
      <%= f.input :photo, label: "Main Image", required: true, as: :file , class: "btn btn-outline-danger mb-3" %>
      <%= f.input :photos, label: "Additional photos", required: false, as: :file , input_html: { multiple: true }, class: "btn btn-outline-danger mb-3" %>
      <%= f.submit "Add Costume", class: "btn btn-outline-danger mb-3"%>
    <% end %>
  </div>
</div>

app/views/costumes/index.html.erb
<section class="section-pagetop bg">
  <div class="container">
    <h2 class="title-page">Find your Costume!</h2>

  </div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
  <div class="container">

    <div class="row">
      <aside class="col-md-3">

        <div class="card">
          <article class="filter-group">
            <header class="card-header">
              <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                <i class="icon-control fa fa-chevron-down"></i>
                <h6 class="title" style="color: green;">Categories</h6>
              </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
              <div class="card-body">

                <ul class="list-menu">
                  <li><a href="{% url 'store' %}">Todos</a></li>
                  <li><a href="/costumes?category=Heroes"> Heroes </a></li>
                  <li><a href="/costumes?category=Horror"> Horror </a></li>
                  <li><a href="/costumes?category=Movies"> Movies </a></li>
                  <li><a href="/costumes?category=Animals"> Animals </a></li>
                  <li><a href="/costumes?category=Anime"> Anime </a></li>
                  <li><a href="/costumes?category=TV+Show"> TV Show </a></li>
                  <li><a href="/costumes?category=Historical+Figures"> Historical </a></li>
                  <li><a href="/costumes?category=Princess"> Princess </a></li>
                  <li><a href="/costumes?category=Cartoon"> Cartoon </a></li>
                </ul>

              </div> <!-- card-body.// -->
            </div>
          </article> <!-- filter-group  .// -->
          <article class="filter-group">
            <header class="card-header">
              <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                <i class="icon-control fa fa-chevron-down"></i>
                <h6 class="title" style="color: green;">Sizes </h6>
              </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4" style="">
              <div class="card-body">
                <label class="checkbox-btn">
                  <input type="checkbox">
                  <span class="btn btn-light"> XS </span>
                </label>

                <label class="checkbox-btn">
                  <input type="checkbox">
                  <span class="btn btn-light"> SM </span>
                </label>

                <label class="checkbox-btn">
                  <input type="checkbox">
                  <span class="btn btn-light"> LG </span>
                </label>

                <label class="checkbox-btn">
                  <input type="checkbox">
                  <span class="btn btn-light"> XXL </span>
                </label>
              </div><!-- card-body.// -->
            </div>
          </article> <!-- filter-group .// -->

          <article class="filter-group">
            <header class="card-header">
              <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                <i class="icon-control fa fa-chevron-down"></i>
                <h6 class="title" style="color: green;">Prices </h6>
              </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
              <div class="card-body">

                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label>Min</label>
                    <!-- <input class="form-control" placeholder="$0" type="number"> -->
                    <select class="mr-2 form-control">
                      <option value="0">$0</option>
                      <option value="50">$50</option>
                      <option value="100">$100</option>
                      <option value="150">$150</option>
                      <option value="200">$200</option>
                      <option value="500">$500</option>
                      <option value="1000">$1000</option>
                    </select>
                  </div>
                  <div class="form-group text-right col-md-6">
                    <label>Max</label>
                    <select class="mr-2 form-control">
                      <option value="50">$50</option>
                      <option value="100">$100</option>
                      <option value="150">$150</option>
                      <option value="200">$200</option>
                      <option value="500">$500</option>
                      <option value="1000">$1000</option>
                      <option value="2000">$2000+</option>
                    </select>
                  </div>
                </div> <!-- form-row.// -->
                <button class="btn btn-block btn-outline-secondary mt-1">Search</button>
              </div><!-- card-body.// -->
            </div>
          </article> <!-- filter-group .// -->

        </div> <!-- card.// -->

      </aside> <!-- col.// -->
      <main class="col-md-9">

        <header class="border-bottom mb-4 pb-3">
          <div class="form-inline">
            <span class="mr-md-auto">  <b><%= @costumes.size %></b> Products Found </span>

          </div>
        </header><!-- sect-heading -->

        <div class="row">
          <% if @costumes.size > 0 %>
          <% @costumes.each do |costume| %>
          <div class="col-md-4">
            <figure class="card card-product-grid">
              <div class="img-wrap">

                <%= link_to costume_path(id:costume, query: params[:query]) do %>
                  <%= cl_image_tag costume.photo.key, gravity: :face, crop: :fill %></a>
                <% end %>

              </div> <!-- img-wrap.// -->
              <figcaption class="info-wrap">
                <div class="fix-height">
                  <strong><%= costume.name %></strong>
                  <div class="price-wrap mt-2">
                    <span class="price">$<%= costume.price %>/ day</span>
                  </div> <!-- price-wrap.// -->
                </div>
                <% if user_signed_in? %>
                  <%= link_to "View Details", costume_path(id:costume, query: params[:query]), class: "btn btn-block btn-success" %>
                <% else %>
                  <%= link_to "View Details", new_user_session_path, class: "btn btn-block btn-success" %>
                <% end %>
              </figcaption>
            </figure>
          </div> <!-- col.// -->
          <% end %>
          <% else %>
            <div>
                <h2> No results found </h2>
            </div>
          <% end %>

        </div> <!-- row end.// -->

      </main> <!-- col.// -->

    </div>

  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

app/views/costumes/new.html.erb
<div class="container">
  <%= render "costumes/new_costume_form", :costume => @costume%>
</div>

app/views/costumes/show.html.erb
<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              <center>
                <div class="img-magnifier-container">
                  <%= cl_image_tag @costume.photo.key, gravity: :face, crop: :fill %>
                </div>
              </center>
            </div> <!-- img-big-wrap.// -->

          </article> <!-- gallery-wrap .end// -->

          <ul class="thumb">
              <li>
                  <%= link_to @costume.photo.key, target: "mainImage" do %>
                    <%= cl_image_tag @costume.photo.key, gravity: :face, crop: :fill, alt: "Product Image" %>
                  <% end %>
                  <% @costume.photos.each do |photo| %>
                    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                  <% end %>
              </li>
          </ul>

        </aside>
        <main class="col-md-6 border-left">

          <% if(@costume.user != current_user) %>
            <%= render "bookings/form" %>
          <% else %>
            <div class="col-md-6 mt-1">
          <h5><strong><%= @costume.name %></h5>
          </strong>
          <div class="d-flex flex-row">
            <div class="ratings mr-2"><i class="fas fa-star"></i><%= @costume.average_rating %></div>
          </div>
          <div class="mt-1 mb-1 spec-1"><em><%= @costume.user.address %></em></div>
          <div class="mt-1 mb-1 spec-1"><strong><%= @costume.category %></strong></div>
          <div class="mt-1 mb-1 spec-1"><%= @costume.description %></div>
        </div>
        <div class="align-items-center align-content-center col-md-3 border-left mt-1">
          <div class="d-flex flex-row align-items-center">
            <h5><strong>$<%= @costume.price %>/day</strong></h5>
          </div>
          <h6 class="text-success">Free shipping</h6>
          <div class="row">
            <% if @costume.user == current_user %>
              <%= button_to "Edit", edit_costume_path(@costume), method: :patch, class: "col btn btn-outline-danger btn-sm mt-2" %>
              <%= button_to "Remove", costume_path(@costume), method: :delete, class: "col btn btn-outline-danger btn-sm mt-2"%>
            <% else %>
            <br>
            <% end %>
          </div>
          </div>
          <% end%>

        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br>

    <div class="row">
      <div class="col-md-9">
      <% if current_user != @costume.user %>
       <div class="container justify-content-center">
        <%= simple_form_for [@costume, @review] do |f| %>
        <%= f.input :rating, collection: 0..5, include_blank: false %>
        <%= f.input :content %>
        <%= f.submit class: "btn btn-outline-danger btn-block" %>
        <% end %>
       </div>
      <% end %>
      <div class="container mt-3">
        <% @costume.reviews.reverse.each do |review| %>
          <div class="box mb-3">
            <div class="icontext w-100">
              <div class="text">
                <img src='https://kitt.lewagon.com/placeholder/users/random' class="avatar-large" />
                <h6 class="mb-1"><%= review.costume.user.email %></h6>
                <span class="date text-muted float-md-right"><%= review.created_at.strftime("%Y-%m-%d") %></span>
                <p><%= review.content %></p>
                <div class="d-flex rating-star">
                  <p><% review.rating.times do %></p>
                    <i class="fas fa-star"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>


      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>

<!-- ========================= SECTION CONTENT END// ========================= -->

app/views/pages/profile.html.erb
<div class="container">
  <div class="card">
    <%= render 'bookings/user_profile' %>
  </div>
</div>
<div class="container">
  <div class="container">
    <h2>Booking Status</h2>
  </div>
    <%= render "bookings/booking_show_card" %>
</div>

app/views/reviews/new.html.erb
<div class="container justify-content-center">
  <div class="card p-3">
    <div id="demo" class="collapse">
      <%= simple_form_for [@costume, @review] do |f| %>
        <%= f.input :rating, collection: 0..5, include_blank: false %>
        <%= f.input :content %>
        <%= f.submit class: "btn btn-outline-danger btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <div class="d-flex gap-3">
      <%= image_tag "logoH.png" %>
      <h1 class="mt-2" style="color: white;">Halloween Time</h1>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <%= form_tag costumes_path, class: "d-flex", role: "search", id: "letters", method: :get do %>
        <%= text_field_tag :query, params[:query], id:"banner-typed-text", class: "form-control me-2", style:"background-color: none", type: "search", placeholder: "Search for costumes"  %>
        <%= submit_tag "Search", class:"btn btn-outline-secondary" %>
      <% end %>
      <li class="navbar-link">
          <%= link_to "Home", "/" %>
      </li>
      <% if user_signed_in? %>
      <li class="navbar-link-d dropdown-center">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        </a>
        <ul class="dropdown-menu">
            <%= link_to "Create Costume", new_costume_path, class: "dropdown-item" %>
            <%= link_to "Manage Bookings", bookings_path, class: "dropdown-item" %>
            <a href="/profile" class="dropdown-item">Profile</a>
            <li><hr class="dropdown-divider"></li>
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </ul>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: {toggle: "dropdown"}, 'aria-haspopup': true, 'aria-expanded': false, gravity: :face, crop: :fill%>
        <% else %>
          <img src="https://kitt.lewagon.com/placeholder/users/random" class="card-trip-user avatar-bordered dropdown-toggle mr-2", id= "navbarDropdown", data-toggle= "dropdown", aria-haspopup="true", aria-expanded="false" />
        <% end %>
      </li>
      <% else %>
        <li class="navbar-link">
          <%= link_to "Login", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
      <% end %>
    </div>
  </div>
</div>